name: Branch Build

on:
  push:
    branches:
      - feature/*

jobs:
  build_project:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - run: docker run --rm pepperdash/sspbuilder dir
        env:
          GITHUB_WORKSPACE: ${{env.GITHUB_WORKSPACE}}
