name: Branch Build

on:
  push:
    branches:
      - feature/*

jobs:
  build_project:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - run: Write-Output "$($Env:GITHUB_WORKSPACE)"
      - run: Invoke-Expression "dir $($Env:GITHUB_WORKSPACE)"
     
