name: Branch Build

on:
  push:
    branches:
      - feature/*

jobs:
  build_project:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - run: echo "${{ env.GITHUB_WORKSPACE }}\pepperdash-generic-colorlightZ6-epi\pepperdash-generic-colorlightZ6-epi.sln"
      - run: docker run --rm pepperdash/sspbuilder c:\cihelpers\vsidebuild.exe -Solution "${{ env.GITHUB_WORKSPACE }}\pepperdash-generic-colorlightZ6-epi\pepperdash-generic-colorlightZ6-epi.sln" -BuildSolutionConfiguration Debug
        env:
          GITHUB_WORKSPACE: GITHUB_WORKSPACE
